#:schema node_modules/wrangler/config-schema.json
# change this name to create a new domain to deploy
name = "security-demo"
main = "src/index.ts"
workers_dev = true
compatibility_date = "2024-08-06"
compatibility_flags = ["nodejs_compat"]
